import { POOL_KEY_COMPONENTS } from './pool-key';

export const V4_AGENTIC_VAULT_ABI = [
	{
		type: 'constructor',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: '_owner', type: 'address' },
			{ name: '_agent', type: 'address' },
			{ name: '_posm', type: 'address' },
			{ name: '_universalRouter', type: 'address' },
			{ name: '_permit2', type: 'address' },
			{
				name: '_poolKey',
				type: 'tuple',
				components: POOL_KEY_COMPONENTS,
			},
			{ name: '_initialAllowedTickLower', type: 'int24' },
			{ name: '_initialAllowedTickUpper', type: 'int24' },
			{ name: '_swapAllowed', type: 'bool' },
			{ name: '_maxPositionsK', type: 'uint256' },
		],
	},
	{
		type: 'receive',
		stateMutability: 'payable',
	},
	{
		type: 'event',
		name: 'AgentUpdated',
		inputs: [{ name: 'newAgent', type: 'address', indexed: true }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'AgentPaused',
		inputs: [{ name: 'paused', type: 'bool', indexed: false }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SwapAllowed',
		inputs: [{ name: 'allowed', type: 'bool', indexed: false }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'AllowedTickRangeUpdated',
		inputs: [
			{ name: 'tickLower', type: 'int24', indexed: false },
			{ name: 'tickUpper', type: 'int24', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'MaxPositionsKUpdated',
		inputs: [{ name: 'k', type: 'uint256', indexed: false }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'PositionAdded',
		inputs: [
			{ name: 'tokenId', type: 'uint256', indexed: true },
			{ name: 'tickLower', type: 'int24', indexed: false },
			{ name: 'tickUpper', type: 'int24', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'PositionRemoved',
		inputs: [{ name: 'tokenId', type: 'uint256', indexed: true }],
		anonymous: false,
	},
	{
		type: 'function',
		name: 'posm',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'universalRouter',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'permit2',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'currency0',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'currency1',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'fee',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'uint24' }],
	},
	{
		type: 'function',
		name: 'tickSpacing',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'int24' }],
	},
	{
		type: 'function',
		name: 'hooks',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'poolId',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'bytes32' }],
	},
	{
		type: 'function',
		name: 'allowedTickLower',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'int24' }],
	},
	{
		type: 'function',
		name: 'allowedTickUpper',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'int24' }],
	},
	{
		type: 'function',
		name: 'maxPositionsK',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'agent',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'agentPaused',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'bool' }],
	},
	{
		type: 'function',
		name: 'swapAllowed',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'bool' }],
	},
	{
		type: 'function',
		name: 'positionIds',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'isManagedPosition',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'bool' }],
	},
	{
		type: 'function',
		name: 'positionTickLower',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'int24' }],
	},
	{
		type: 'function',
		name: 'positionTickUpper',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'int24' }],
	},
	{
		type: 'function',
		name: 'setAgent',
		stateMutability: 'nonpayable',
		inputs: [{ name: 'newAgent', type: 'address' }],
		outputs: [],
	},
	{
		type: 'function',
		name: 'setAgentPaused',
		stateMutability: 'nonpayable',
		inputs: [{ name: 'paused', type: 'bool' }],
		outputs: [],
	},
	{
		type: 'function',
		name: 'setSwapAllowed',
		stateMutability: 'nonpayable',
		inputs: [{ name: 'allowed', type: 'bool' }],
		outputs: [],
	},
	{
		type: 'function',
		name: 'setAllowedTickRange',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tickLower', type: 'int24' },
			{ name: 'tickUpper', type: 'int24' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'setMaxPositionsK',
		stateMutability: 'nonpayable',
		inputs: [{ name: 'k', type: 'uint256' }],
		outputs: [],
	},
	{
		type: 'function',
		name: 'approveTokenWithPermit2',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'currency', type: 'address' },
			{ name: 'spender', type: 'address' },
			{ name: 'amount', type: 'uint160' },
			{ name: 'expiration', type: 'uint48' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'withdraw',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'currency', type: 'address' },
			{ name: 'amount', type: 'uint256' },
			{ name: 'to', type: 'address' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'pauseAndExitAll',
		stateMutability: 'nonpayable',
		inputs: [{ name: 'deadline', type: 'uint256' }],
		outputs: [],
	},
	{
		type: 'function',
		name: 'mintPosition',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tickLower', type: 'int24' },
			{ name: 'tickUpper', type: 'int24' },
			{ name: 'liquidity', type: 'uint256' },
			{ name: 'amount0Max', type: 'uint128' },
			{ name: 'amount1Max', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [{ name: 'tokenId', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'increaseLiquidity',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'liquidity', type: 'uint256' },
			{ name: 'amount0Max', type: 'uint128' },
			{ name: 'amount1Max', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'decreaseLiquidityToVault',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'liquidity', type: 'uint256' },
			{ name: 'amount0Min', type: 'uint128' },
			{ name: 'amount1Min', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'collectFeesToVault',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'amount0Min', type: 'uint128' },
			{ name: 'amount1Min', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'burnPositionToVault',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'amount0Min', type: 'uint128' },
			{ name: 'amount1Min', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'swapExactInputSingle',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: 'zeroForOne', type: 'bool' },
			{ name: 'amountIn', type: 'uint128' },
			{ name: 'minAmountOut', type: 'uint128' },
			{ name: 'deadline', type: 'uint256' },
		],
		outputs: [{ name: 'amountOut', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'getPoolKey',
		stateMutability: 'view',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'tuple',
				components: POOL_KEY_COMPONENTS,
			},
		],
	},
	{
		type: 'function',
		name: 'positionsLength',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'onERC721Received',
		stateMutability: 'pure',
		inputs: [
			{ name: '', type: 'address' },
			{ name: '', type: 'address' },
			{ name: '', type: 'uint256' },
			{ name: '', type: 'bytes' },
		],
		outputs: [{ name: '', type: 'bytes4' }],
	},
] as const;
