import { POOL_KEY_COMPONENTS } from './pool-key';

export const V4_AGENTIC_VAULT_FACTORY_ABI = [
	{
		type: 'constructor',
		stateMutability: 'nonpayable',
		inputs: [
			{ name: '_posm', type: 'address' },
			{ name: '_universalRouter', type: 'address' },
			{ name: '_permit2', type: 'address' },
		],
	},
	{
		type: 'event',
		name: 'VaultCreated',
		inputs: [
			{ name: 'creator', type: 'address', indexed: true },
			{ name: 'vault', type: 'address', indexed: true },
			{
				name: 'poolKey',
				type: 'tuple',
				indexed: false,
				components: POOL_KEY_COMPONENTS,
			},
			{ name: 'agent', type: 'address', indexed: false },
			{ name: 'nonce', type: 'uint256', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'function',
		name: 'posm',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'universalRouter',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'permit2',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'vaults',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'vaultsCreatedBy',
		stateMutability: 'view',
		inputs: [
			{ name: '', type: 'address' },
			{ name: '', type: 'uint256' },
		],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'isVault',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'address' }],
		outputs: [{ name: '', type: 'bool' }],
	},
	{
		type: 'function',
		name: 'creatorNonce',
		stateMutability: 'view',
		inputs: [{ name: '', type: 'address' }],
		outputs: [{ name: '', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'createVault',
		stateMutability: 'nonpayable',
		inputs: [
			{
				name: 'poolKey',
				type: 'tuple',
				components: POOL_KEY_COMPONENTS,
			},
			{ name: 'agent', type: 'address' },
			{ name: 'allowedTickLower', type: 'int24' },
			{ name: 'allowedTickUpper', type: 'int24' },
			{ name: 'swapAllowed', type: 'bool' },
			{ name: 'maxPositionsK', type: 'uint256' },
		],
		outputs: [{ name: 'vault', type: 'address' }],
	},
	{
		type: 'function',
		name: 'computeVaultAddress',
		stateMutability: 'view',
		inputs: [
			{ name: 'creator', type: 'address' },
			{
				name: 'poolKey',
				type: 'tuple',
				components: POOL_KEY_COMPONENTS,
			},
			{ name: 'nonce', type: 'uint256' },
			{ name: 'agent', type: 'address' },
			{ name: 'allowedTickLower', type: 'int24' },
			{ name: 'allowedTickUpper', type: 'int24' },
			{ name: 'swapAllowed', type: 'bool' },
			{ name: 'maxPositionsK', type: 'uint256' },
		],
		outputs: [{ name: '', type: 'address' }],
	},
	{
		type: 'function',
		name: 'getVaultsCreatedBy',
		stateMutability: 'view',
		inputs: [{ name: 'creator', type: 'address' }],
		outputs: [{ name: '', type: 'address[]' }],
	},
	{
		type: 'function',
		name: 'getAllVaults',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'address[]' }],
	},
	{
		type: 'function',
		name: 'totalVaults',
		stateMutability: 'view',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
	},
	{
		type: 'function',
		name: 'getNextNonce',
		stateMutability: 'view',
		inputs: [{ name: 'creator', type: 'address' }],
		outputs: [{ name: '', type: 'uint256' }],
	},
] as const;
