/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectWalletRouteImport } from './routes/connect-wallet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsVaultIdRouteImport } from './routes/vaults/$vaultId'

const ConnectWalletRoute = ConnectWalletRouteImport.update({
  id: '/connect-wallet',
  path: '/connect-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsVaultIdRoute = VaultsVaultIdRouteImport.update({
  id: '/vaults/$vaultId',
  path: '/vaults/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-wallet': typeof ConnectWalletRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-wallet': typeof ConnectWalletRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-wallet': typeof ConnectWalletRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect-wallet' | '/vaults/$vaultId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect-wallet' | '/vaults/$vaultId'
  id: '__root__' | '/' | '/connect-wallet' | '/vaults/$vaultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectWalletRoute: typeof ConnectWalletRoute
  VaultsVaultIdRoute: typeof VaultsVaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connect-wallet': {
      id: '/connect-wallet'
      path: '/connect-wallet'
      fullPath: '/connect-wallet'
      preLoaderRoute: typeof ConnectWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$vaultId': {
      id: '/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof VaultsVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectWalletRoute: ConnectWalletRoute,
  VaultsVaultIdRoute: VaultsVaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
